# Auto-generated spaCy training data from Label Studio
TRAIN_DATA = [

    ("            Chatterbox feels that the Wall Street Journal editorial page's", {'entities': [(38, 57, 'ORG')]}),
    ("coverage of Juanita Broaddrick's rape charges against Bill Clinton (see", {'entities': [(54, 66, 'PERSON'), (12, 30, 'PERSON')]}),
    ("Rape,\" as well as Michael Kinsley's", {'entities': [(18, 33, 'PERSON')]}),
    ("of Joseph Stalin. (Chatterbox would prefer not to invoke the phrase", {'entities': [(3, 16, 'PERSON')]}),
    ("            For the purposes of this survey, the Wall Street Journal will be", {'entities': [(49, 68, 'ORG')]}),
    ("            The Journal editorial page continues not to acknowledge that Norma", {'entities': [(12, 38, 'ORG'), (73, 78, 'PERSON')]}),
    ("Kelsey, the friend and employee to Juanita Broaddrick who is one of two people", {'entities': [(0, 6, 'PERSON'), (35, 53, 'PERSON')]}),
    ("whose murderer was pardoned by Gov. Bill Clinton. (A responsible account of the", {'entities': [(31, 48, 'PERSON')]}),
    ("whole controversy in today's New York Times reports that Kelsey says the pardon", {'entities': [(29, 43, 'ORG'), (57, 63, 'PERSON')]}),
    ("had nothing to do with her corroboration.) The Journal editorial page", {'entities': [(43, 69, 'ORG')]}),
    ("Dorothy Rabinowitz on Feb. 19. Because it has published three times since the", {'entities': [(0, 18, 'PERSON')]}),
    ("tomorrow to tonight's NBC broadcast of its own Broaddrick interview, which", {'entities': [(22, 25, 'ORG'), (47, 57, 'PERSON')]}),
    ("means that if the Journal editorial page continues to take no action it", {'entities': [(14, 40, 'ORG')]}),
    ("            Chatterbox considered but rejected the idea of awarding Rabinowitz bonus", {'entities': [(68, 78, 'PERSON')]}),
    ("points for having \"eventually convinced\" Broaddrick to grant an interview to", {'entities': [(41, 51, 'PERSON')]}),
    ("the New York Times (as the Times reports in today's story). But", {'entities': [(0, 18, 'ORG')]}),
    ("            Chatterbox feels that the Wall Street Journal editorial page's", {"entities": [(38, 57, 'ORG')]}),
    ("coverage of Juanita Broaddrick's rape charges against Bill Clinton (see", {"entities": [(54, 66, 'PERSON'), (12, 30, 'PERSON')]}),
    ("Rape,\" as well as Michael Kinsley's", {"entities": [(18, 33, 'PERSON')]}),
    ("of Joseph Stalin. (Chatterbox would prefer not to invoke the phrase", {"entities": [(3, 16, 'PERSON')]}),
    ("            For the purposes of this survey, the Wall Street Journal will be", {"entities": [(49, 68, 'ORG')]}),
    ("            The Journal editorial page continues not to acknowledge that Norma", {"entities": [(12, 38, 'ORG'), (73, 78, 'PERSON')]}),
    ("Kelsey, the friend and employee to Juanita Broaddrick who is one of two people", {"entities": [(0, 6, 'PERSON'), (35, 53, 'PERSON')]}),
    ("whose murderer was pardoned by Gov. Bill Clinton. (A responsible account of the", {"entities": [(31, 48, 'PERSON')]}),
    ("whole controversy in today's New York Times reports that Kelsey says the pardon", {"entities": [(29, 43, 'ORG'), (57, 63, 'PERSON')]}),
    ("had nothing to do with her corroboration.) The Journal editorial page", {"entities": [(43, 69, 'ORG')]}),
    ("Dorothy Rabinowitz on Feb. 19. Because it has published three times since the", {"entities": [(0, 18, 'PERSON')]}),
    ("tomorrow to tonight's NBC broadcast of its own Broaddrick interview, which", {"entities": [(22, 25, 'ORG'), (47, 57, 'PERSON')]}),
    ("means that if the Journal editorial page continues to take no action it", {"entities": [(14, 40, 'ORG')]}),
    ("            Chatterbox considered but rejected the idea of awarding Rabinowitz bonus", {"entities": [(68, 78, 'PERSON')]}),
    ("points for having \"eventually convinced\" Broaddrick to grant an interview to", {"entities": [(41, 51, 'PERSON')]}),
    ("the New York Times (as the Times reports in today's story). But", {"entities": [(0, 18, 'ORG')]}),
]
